package com.job.portal.pojo;
// Generated Apr 4, 2016 11:54:04 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Future;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

/**
 * Appliedjobs generated by hbm2java
 */
@Entity
@Table(name = "appliedjobs", catalog = "jobportal")
// , uniqueConstraints = @UniqueConstraint(columnNames = "referenceID")
public class Appliedjobs implements java.io.Serializable {

	private int id;

	private int jobSeekerId;
	private int jobId;
	// private AppliedjobsId id;
	private Job job;
	private JobSeeker jobseeker;
	private Date appliedDate;

	private Date availableFrom;
	private String resumeFileName;

	private String legallyAuthorized;

	private String sponsorship;

	private String citizen;

	private String veteran;
	private JobapplicationStatusCode jobApplicationStatusCode;

	private MultipartFile resumeFile;

	public Appliedjobs() {

	}

	public Appliedjobs(int id, Job job, JobapplicationStatusCode jobApplicationStatusCode, JobSeeker jobseeker,
			Date appliedDate, Date availableFrom, String resumeFileName, String legallyAuthorized, String sponsorship,
			String citizen, String veteran) {
		this.jobApplicationStatusCode = jobApplicationStatusCode;
		this.id = id;
		this.job = job;
		this.jobseeker = jobseeker;
		this.appliedDate = appliedDate;
		this.availableFrom = availableFrom;
		this.resumeFileName = resumeFileName;
		this.legallyAuthorized = legallyAuthorized;
		this.sponsorship = sponsorship;
		this.citizen = citizen;
		this.veteran = veteran;
	}

	// @EmbeddedId
	//
	// @AttributeOverrides({
	// @AttributeOverride(name = "jobSeekerId", column = @Column(name =
	// "jobSeekerID", nullable = false)),
	// @AttributeOverride(name = "jobId", column = @Column(name = "jobID",
	// nullable = false)),
	// @AttributeOverride(name = "referenceId", column = @Column(name =
	// "referenceID", unique = true, nullable = false)) })
	// public AppliedjobsId getId() {
	// return this.id;
	// }
	//
	// public void setId(AppliedjobsId id) {
	// this.id = id;
	// }
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "appliedjobID", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getJobSeekerId() {
		return jobSeekerId;
	}

	public void setJobSeekerId(int jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	public int getJobId() {
		return jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "jobID", nullable = false, insertable = false, updatable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "statusID", nullable = false)
	public JobapplicationStatusCode getJobApplicationStatusCode() {
		return jobApplicationStatusCode;
	}

	public void setJobApplicationStatusCode(JobapplicationStatusCode jobApplicationStatusCode) {
		this.jobApplicationStatusCode = jobApplicationStatusCode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "jobSeekerID", nullable = false, insertable = false, updatable = false)
	public JobSeeker getJobseeker() {
		return this.jobseeker;
	}

	public void setJobseeker(JobSeeker jobseeker) {
		this.jobseeker = jobseeker;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "appliedDate", nullable = false, length = 10)
	public Date getAppliedDate() {
		return this.appliedDate;
	}

	public void setAppliedDate(Date appliedDate) {
		this.appliedDate = appliedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "availableFrom", nullable = false, length = 10)
	public Date getAvailableFrom() {
		return this.availableFrom;
	}

	public void setAvailableFrom(Date availableFrom) {
		this.availableFrom = availableFrom;
	}

	@Column(name = "resumeFileName", nullable = false)
	public String getResumeFileName() {
		return this.resumeFileName;
	}

	public void setResumeFileName(String resumeFileName) {
		this.resumeFileName = resumeFileName;
	}

	@Column(name = "legally_authorized", nullable = false, length = 3)
	public String getLegallyAuthorized() {
		return this.legallyAuthorized;
	}

	public void setLegallyAuthorized(String legallyAuthorized) {
		this.legallyAuthorized = legallyAuthorized;
	}

	@Column(name = "sponsorship", nullable = false, length = 3)
	public String getSponsorship() {
		return this.sponsorship;
	}

	public void setSponsorship(String sponsorship) {
		this.sponsorship = sponsorship;
	}

	@Column(name = "citizen", nullable = false, length = 3)
	public String getCitizen() {
		return this.citizen;
	}

	public void setCitizen(String citizen) {
		this.citizen = citizen;
	}

	@Column(name = "veteran", nullable = false, length = 10)
	public String getVeteran() {
		return this.veteran;
	}

	public void setVeteran(String veteran) {
		this.veteran = veteran;
	}

	@Transient
	public MultipartFile getResumeFile() {
		return resumeFile;
	}

	public void setResumeFile(MultipartFile resumeFile) {
		this.resumeFile = resumeFile;
	}
}
