package com.job.portal.pojo;
// Generated Apr 4, 2016 11:54:04 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppliedjobsId generated by hbm2java
 */
@Embeddable
public class AppliedjobsId implements java.io.Serializable {

	private int jobSeekerId;
	private int jobId;
	private int referenceId;

	public AppliedjobsId() {
	}

	public AppliedjobsId(int jobSeekerId, int jobId, int referenceId) {
		this.jobSeekerId = jobSeekerId;
		this.jobId = jobId;
		this.referenceId = referenceId;
	}

	@Column(name = "jobSeekerID", nullable = false)
	public int getJobSeekerId() {
		return this.jobSeekerId;
	}

	public void setJobSeekerId(int jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	@Column(name = "jobID", nullable = false)
	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	@Column(name = "referenceID", unique = true, nullable = false)
	public int getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(int referenceId) {
		this.referenceId = referenceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppliedjobsId))
			return false;
		AppliedjobsId castOther = (AppliedjobsId) other;

		return (this.getJobSeekerId() == castOther.getJobSeekerId()) && (this.getJobId() == castOther.getJobId())
				&& (this.getReferenceId() == castOther.getReferenceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJobSeekerId();
		result = 37 * result + this.getJobId();
		result = 37 * result + this.getReferenceId();
		return result;
	}

}
