package com.job.portal.pojo;
// Generated Apr 4, 2016 11:54:04 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name = "employer", catalog = "jobportal")
public class Employer implements java.io.Serializable {

	private Integer employerId;
	private Adminapprovalstatuscode adminapprovalstatuscode;
	@Valid
	private User user;
	@NotBlank
	@Size(min = 2,max = 100, message="Company Name must be between {min} and {max} characters long")
	private String companyName;
	@NotBlank
	@Size(min=10,max=10,message="Phone Number must be 10 digits")
	private String phone;
	private List<Job> jobs = new ArrayList<Job>(0);

	public Employer() {
	}

	public Employer(Adminapprovalstatuscode adminapprovalstatuscode, User user, String companyName, String phone) {
		this.adminapprovalstatuscode = adminapprovalstatuscode;
		this.user = user;
		this.companyName = companyName;
		this.phone = phone;
	}

	public Employer(Adminapprovalstatuscode adminapprovalstatuscode, User user, String companyName, String phone,
			List<Job> jobs) {
		this.adminapprovalstatuscode = adminapprovalstatuscode;
		this.user = user;
		this.companyName = companyName;
		this.phone = phone;
		this.jobs = jobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "employerID", unique = true, nullable = false)
	public Integer getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Integer employerId) {
		this.employerId = employerId;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "statusID", nullable = false)
	public Adminapprovalstatuscode getAdminapprovalstatuscode() {
		return this.adminapprovalstatuscode;
	}

	public void setAdminapprovalstatuscode(Adminapprovalstatuscode adminapprovalstatuscode) {
		this.adminapprovalstatuscode = adminapprovalstatuscode;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "companyName", nullable = false, length = 200)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employer")
	public List<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(List<Job> jobs) {
		this.jobs = jobs;
	}

}
