package com.job.portal.pojo;
// Generated Apr 13, 2016 5:07:28 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobtype generated by hbm2java
 */
@Entity
@Table(name = "jobtype", catalog = "jobportal")
public class Jobtype implements java.io.Serializable {

	private Integer jobTypeID;
	private String name;
	private Set<Job> jobs = new HashSet<Job>(0);

	public Jobtype() {
	}

	public Jobtype(String name) {
		this.name = name;
	}

	public Jobtype(String name, Set<Job> jobs) {
		this.name = name;
		this.jobs = jobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.jobTypeID;
	}

	public void setId(Integer jobTypeID) {
		this.jobTypeID = jobTypeID;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "jobtype")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

}
