package com.job.portal.pojo;
// Generated Apr 4, 2016 11:54:04 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "jobportal")
public class Location implements java.io.Serializable {

	private Integer locationId;
	@Size(min = 2,max = 100, message="City Name must be between {min} and {max} characters long")
	private String city;
	@Size(min = 2,max = 2, message="State Name must be {max} characters long")
	private String stateName;
	private Set<Job> jobs = new HashSet<Job>(0);

	public Location() {
	}

	public Location(String city, String stateName) {
		this.city = city;
		this.stateName = stateName;
	}

	public Location(String city, String stateName, Set<Job> jobs) {
		this.city = city;
		this.stateName = stateName;
		this.jobs = jobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "locationID", unique = true, nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "stateName", nullable = false, length = 2)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "location")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

}
